// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "./LotteryStructs.sol";

/*
    Custom ERC20 token for the lottery system.
*/
contract TicketToken is ERC20 {
    address public owner; // address of the contract owner

    /*
        Sets up the token with a name and symbol, and assigns the owner.
        Inherits ERC20 constructor for token initialization
    */
    constructor() ERC20("NuBaGo Token", "NBG") {
        owner = msg.sender;
    }

    /*
        // TODO: enough?
        @param to the address to receive the tokens
        @param amount number of tokens to get
    */
    function mint(address to, uint256 amount) external {
        require(msg.sender == owner, "Only the owner can mint tickets");
        _mint(to, amount);
    }
}

/*
    This contract manages lotteries using ERC20 token.
    TODO: Explain more
*/
contract NBGLottery {

    using LotteryStructs for *; // Using the LotteryInfo, TicketInfo structs and LotteryState enum

    TicketToken public ticketToken;
    address public owner;
    uint32 public currentLotteryNo;

    mapping(uint32 => LotteryStructs.LotteryInfo) public lotteries; // Mapping of lottery IDs to LotteryInfo

    // TODO tek bir lottery olacağı için map yerine array kullanılabilir ??
    mapping(uint => LotteryStructs.TicketInfo[]) public lotteryTickets; // Mapping of lottery IDs to an array of TicketInfo structs

    event TicketPurchased(uint lotteryNo, uint ticketNo, uint8 quantity);

    /*
        Sets the owner and initializes TicketToken contract.
        @param _ticketTokenAddress address of the deployed TicketToken contract
    */
    constructor(address _ticketTokenAddress) {
        owner = msg.sender;
        ticketToken = TicketToken(_ticketTokenAddress);
    }

    /*
        TODO comment
        @param quantity number of tickets to be purchased
        @param hash_rnd_number hash generated by the user by using their address and random number
        @return sticketno
    */
    function buyTicketTx(uint8 quantity, bytes32 hash_rnd_number) public returns(uint sticketno) {
        
        // Check if the lottery is active, lottery is finished, and are there enough tickets to sold
        require(lotteries[currentLotteryNo].state == LotteryStructs.LotteryState.ACTIVE, "Lottery is not active");
        require(block.timestamp < lotteries[currentLotteryNo].unixbeg, "Lottery has ended");
        require(lotteries[currentLotteryNo].soldTickets + quantity <= lotteries[currentLotteryNo].nooftickets, "Not enough tickets available");

        // Calculate total cost
        uint totalCost = quantity * lotteries[currentLotteryNo].ticketprice;
        // ticketToken.transferFrom(msg.sender, owner, totalCost);

        // Construct a ticket with the info provided
        LotteryStructs.TicketInfo memory ticket = LotteryStructs.TicketInfo({
            participant: msg.sender,
            quantity: quantity,
            hash_rnd_number: hash_rnd_number,
            revealed: false
        });

        lotteryTickets[currentLotteryNo].push(ticket);
        sticketno = lotteryTickets[currentLotteryNo].length - 1;

        lotteries[currentLotteryNo].soldTickets += quantity;

        // Log ticket purchased
        emit TicketPurchased(currentLotteryNo, sticketno, quantity);
    }

    /*
    function createLottery(uint unixbeg, uint nooftickets, noofwinners, uint minpercentage, uint ticketprice, bytes32 htmlhash, string url) public onlyOwner returns(uint lottery_no)
    
    function revealRndNumberTx(uint sticketno, quantity, uint rnd_number) public
    function getNumPurchaseTxs(uint lottery_no) public view returns(uint numpurchasetxs)
    function getIthPurchasedTicketTx(uint i,uint lottery_no) public view returns(uint sticketno, uint quantity)
    function checkIfMyTicketWon(uint lottery_no, uint ticket_no) public view returns (bool won)
    function checkIfAddrTicketWon(address addr, uint lottery_no, uint ticket_no) public view returns (bool won)
    function getIthWinningTicket(uint lottery_no,uint i) public view returns (uint ticketno)
    function withdrawTicketRefund(uint lottery_no, uint sticket_no) public
    function getCurrentLotteryNo() public view returns (uint lottery_no)
    function withdrawTicketProceeds(uint lottery_no) public onlyOwner
    function setPaymentToken(address erctokenaddr) public onlyOwner
    function getPaymentToken(uint lottery_no) public returns (address erctokenaddr)
    function getLotteryInfo(uint lottery_no) public returns (uint unixbeg, uint nooftickets, noofwinners, uint minpercentage, uint ticketprice)
    function getLotteryURL(uint lottery_no) public returns(bytes32 htmlhash, string url)
    function getLotterySales(uint lottery_no) public (uint numsold)
    */

}